### ISSUE TITLE
Refused to apply style from style.css because its MIME type ('text/html') is not a supported

### ISSUE THREAD

**Issue by Rachidelmahmoudi** [planetoftheweb/sassbootstrap#2]
Hi.
When I run the npm start in my local I get this error.
The server is runing nice it does not say any issue.
So the project is not reading its css.
That the screenshot of error
Best regards.
![Sans titre11](https://user-images.githubusercontent.com/35012638/80914135-27e20e80-8d39-11ea-8354-82a0623297b1.png)

![screencapture-localhost-8080-2020-05-03-12_19_13](https://user-images.githubusercontent.com/35012638/80914130-244e8780-8d39-11ea-9721-f021fd32f7c6.png)

**Comment by planetoftheweb** [comment]
Can you be more specific...Which branch is this happening in? This error usually means that the file can't be found, so check the links to the file, also quit your terminal or restart vscode again.

**Comment by berdachuk** [comment]
Hi, I have the same problem with LTS node version: node v12.18.2 (npm v6.14.5).
Seems that node-sass doest generate output CSS files, such as there is missing "/css/style.css" in the dist folder

**Comment by planetoftheweb** [comment]
This issue is talked about and solved in #1. TLDR. npm install on the master branch, which is always a good idea anyways.
