### ISSUE TITLE
node-pre-gyp fails on npm install

### ISSUE THREAD

**Issue by dut-a** [planetoftheweb/sassbootstrap#4]
When I run npm install, it keeps failing with the following errors:

`node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v79-darwin-x64.tar.gz

node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@13.7.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)`

I tried node versions 13.1.0, 13.7.0, 13.14.0, 14.5.0 but none of them works. Am I missing the right version of node to run this project on or something else is wrong?

**OS:** **_MacOS MoJave_** (10.14.6)

**Comment by planetoftheweb** [comment]
Have you tried installing under the master branch? See #1

**Comment by dut-a** [comment]
Yes. I cloned the final version which come down with only the master branch. That still failed like branch 01_02b that I first tried.

**Comment by dut-a** [comment]
I got it to run finally. I had to install dependencies (and dev dependencies) one by one; picking the latest versions at the time.

Steps
Packages being too many, I got lazy and went to a browser console.
1. Dev Dependencies
   a. I extracted dev dependencies from _package.json_ and created a variable.
   `let devdep = {
   "@11ty/eleventy": "^0.7.1",
  "@11ty/eleventy-plugin-rss": "^1.0.5",
  "@11ty/eleventy-plugin-syntaxhighlight": "^2.0.1",
  "@fortawesome/fontawesome-free": "^5.7.2",
  "babel-cli": "^6.26.0",
  "babel-preset-es2015": "^6.24.1",
  "css-loader": "^2.1.0",
  "luxon": "^1.11.2",
  "markdown-it": "^8.4.1",
  "markdown-it-anchor": "^5.0.2",
  "node-sass": "^4.11.0",
  "npm-run-all": "^4.1.5",
  "popper.js": "^1.14.7",
  "sass-loader": "^7.1.0",
  "style-loader": "^0.23.1",
  "vue-loader": "^15.6.2",
  "vue-style-loader": "^4.1.2",
  "vue-template-compiler": "^2.6.6",
  "webpack": "^4.29.3",
  "webpack-cli": "other"
}`.

b. I then extracted the keys: `console.log(Object.keys(devdep).join(" "))`.

c. I cleared out the "**devDependencies**" block to remain just _"devDependencies": { }_.

d. I copied the output from **b** above, went to the terminal and issued: `npm i <copied string from browser console>`

2. Dependencies
Repeat steps for Dev Dependencies above with these modifications:
a. `let dep =  {
  "animate.css": "^3.7.0",
  "bootstrap": "^4.3.1",
  "jquery": "^3.5.1",
  "vue": "^2.6.6"
}`
...
c. _"dependencies": { }_

**Comment by planetoftheweb** [comment]
That's super weird. Do you have a link to the fork with the changes you made?

**Comment by planetoftheweb** [comment]
I went through and then npm update to update all of the versions of things to the current. The master branch has the latest versions of everything and things seem to be working at least for me.  Make sure you npm i from master and hopefully that should work. :)
